[project]
name = "carto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "humanize>=4.12.3",
    "lzstring>=1.0.4",
    "pillow>=11.2.1",
    "platformdirs>=4.3.8",
    "psutil>=7.0.0",
    "send2trash>=1.8.3",
    "textual-autocomplete>=4.0.4",
    "textual-dev>=1.7.0",
    "textual-image[textual]>=0.8.2",
    "textual[syntax]>=3.3.0",
    "thefuzz>=0.22.1",
    "toml>=0.10.2",
    "ujson>=5.10.0",
    "watchdog>=6.0.0",
]

[dependency-groups]
dev = [
    "codeflash>=0.13.0",
    "hatch>=1.14.1",
    "isort>=6.0.1",
    "ruff>=0.11.12",
]

[tool.codeflash]
# All paths are relative to this pyproject.toml's directory.
module-root = "src"
tests-root = "tests"
test-framework = "pytest"
benchmarks-root = ""
ignore-paths = []
disable-telemetry = true
formatter-cmds = ["disabled"]
