[project]
name = "carto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "humanize>=4.12.3",
    "pillow>=11.2.1",
    "psutil>=7.0.0",
    "textual[dev,syntax]>=3.2.0",
    "textual-dev>=1.7.0",
    "textual-autocomplete>=4.0.4",
    "textual-image[textual]>=0.8.2",
    "textual-web>=0.4.2",
    "toml>=0.10.2",
    "watchdog>=6.0.0",
    "platformdirs>=4.3.8",
    "thefuzz>=0.22.1",
    "ujson>=5.10.0",
    "lzstring>=1.0.4",
    "send2trash>=1.8.3",
]

[dependency-groups]
dev = [
    "hatch>=1.14.1",
    "ruff>=0.11.10",
]
