[interface]
tooltips = true
nerd_font = false
show_progress_eta = true
show_progress_percentage = true

preview_error = "Hmm, I think this file got corrupted (or maybe not?)"
preview_binary = "This file is not UTF-8 encoded, so I decline to read it."
preview_start = "print(\"Hello, world!\")"

[settings]
use_recycle_bin = true
filelist_sort_by = "name"
filelist_sort_order = "ascending"
preview_full = false


[metadata]
fields = [
    "type",
    "permissions",
    "size",
    "modified",
    "accessed",
    "created",
]
datetime_format = "%Y-%m-%d %H:%M"

[theme]
transparent = false
# if you are using transparent theme, the default theme, or any other custom themes are not used at all
# this is a textual limitation, and the only way you can solve it is by editing the css file
default = "nord"

[[custom_theme]]
name = "High Contrast Dark"
primary = "#ffffff"
secondary = "#cccccc"
accent = "#00ff00"
foreground = "#ffffff"
background = "#000000"
success = "#00ff00"
warning = "#ffff00"
error = "#ff0000"
surface = "#1a1a1a"
panel = "#0d0d0d"
is_dark = true

[keybinds]
toggle_pin = ["P"]
toggle_pinned_sidebar = ["S"]
toggle_preview_sidebar = ["I"]
toggle_footer = ["F"]

focus_toggle_pinned_sidebar = ["s"]
focus_file_list = ["escape"]
focus_toggle_preview_sidebar = ["i"]
focus_toggle_path_switcher = ["slash", "/"]
focus_toggle_search = ["f", "/"]
focus_toggle_processes = ["p"]
focus_toggle_clipboard = ["c"]
focus_toggle_metadata = ["m"]

copy = ["y", "ctrl+c"]
paste = ["p", "ctrl+v"]
cut = ["x", "ctrl+x"]
delete = ["d", "delete"]
rename = ["r", "f2"]
toggle_all = ["%", "ctrl+a"]
new = ["o", "ctrl+n"]

up = ["up", "k"]
down = ["down", "j"]
up_tree = ["left", "h"]
down_tree = ["right", "l", "enter"]
page_up = ["pageup", "ctrl+b"]
page_down = ["pagedown", "ctrl+f"]
home = ["home", "g"]
end = ["end", "G"]
hist_previous = ["backspace", "u"]
hist_next = ["space", "o"]
refresh = ["ctrl+r", "f5"]

toggle_visual = ["v"]
select_up = ["shift+up", "K"]
select_down = ["shift+down", "J"]
select_page_up = ["shift+pageup"]
select_page_down = ["shift+pagedown"]
select_home = ["shift+home"]
select_end = ["shift+end"]

[plugins.zoxide]
enabled = false
keybinds = ["z"]
[plugins.bat]
enabled = false
executable = "bat"
show_line_numbers = true
[plugins.editor]
enabled = false
executable = "nano"
keybinds = ["e"]
