[sidebar]
wrap = true

[filelist]
sort_by = "name"
sort_order = "ascending"

[sidebar.text]
error = "Hmm, I think this file got corrupted (or maybe not?)"
binary = "010101 0101\nJust kidding, this is a binary file"
folder = "Nesting? What's that?"
start = "print(\"Hello, world!\")"

[interface.border]
style = "solid"
inactive_color = "$primary-darken-3"
color = "$primary-lighten-3"

[interface.fractions]
pinned_sidebar = 1
file_list = 3
preview_sidebar = 2

[interface.theme]
default = "nord"

[[interface.custom_theme]]
name = "High Contrast Dark"
primary = "#ffffff"
secondary = "#cccccc"
accent = "#00ff00"
foreground = "#ffffff"
background = "#000000"
success = "#00ff00"
warning = "#ffff00"
error = "#ff0000"
surface = "#1a1a1a"
panel = "#0d0d0d"
is_dark = true

[keybinds]
toggle_pin = ["p"]

[keybinds.focus]
pinned_sidebar = ["s"]
file_list = ["escape"]
preview_sidebar = ["m"]
path_switcher = ["slash", "question_mark"]
search = ["f"]

[keybinds.navigation]
previous = ["backspace"]
next = ["space"]
up = ["shift+up"]
reload = ["ctrl+r"]

[keybinds.mode]
visual = ["v"]

[search]
threshold = 50