[sidebar]
wrap = true

[sidebar.text]
error = "Hmm, I think this file got corrupted (or maybe not?)"
binary = "This file is not UTF-8 encoded, so I decline to read it."
start = "print(\"Hello, world!\")"

[filelist]
sort_by = "name"
sort_order = "ascending"

[interface]
tooltips = true
[interface.border]
style = "solid"
inactive_color = "$primary-darken-3"
color = "$primary-lighten-3"
subtitle = "$primary-muted"

[interface.widths]
pinned_sidebar = "20"
file_list = "3fr"
preview_sidebar = "2fr"
footer_unfocus = "10"
footer_focus = "20"

[interface.theme]
default = "nord"

[[interface.custom_theme]]
name = "High Contrast Dark"
primary = "#ffffff"
secondary = "#cccccc"
accent = "#00ff00"
foreground = "#ffffff"
background = "#000000"
success = "#00ff00"
warning = "#ffff00"
error = "#ff0000"
surface = "#1a1a1a"
panel = "#0d0d0d"
is_dark = true

[keybinds]
toggle_pin = ["P"]

[keybinds.hide]
pinned_sidebar = ["S"]
preview_sidebar = ["I"]
footer = ["F"]

[keybinds.focus]
pinned_sidebar = ["s"]
file_list = ["escape"]
preview_sidebar = ["i"]
path_switcher = ["slash", "question_mark"]
search = ["f"]
processes = ["p"]
clipboard = ["c"]
metadata = ["m"]

[keybinds.manipulation]
copy = ["C"]
paste = ["V"]
cut = ["X"]
delete = ["D"]
rename = ["R"]

[keybinds.navigation]
up = ["up", "k"]
down = ["down", "j"]
up_tree = ["shift+up", "left", "h"]
down_tree = ["enter", "right", "l"]
page_up = ["pageup"]
page_down = ["pagedown"]
home = ["home"]
end = ["end"]
hist_previous = ["backspace"]
hist_next = ["space"]
reload = ["ctrl+r"]

[keybinds.mode]
select = ["v"]

[plugins]
[plugins.zoxide]
enabled = true
keybinds = ["z"]
[plugins.bat]
enabled = true
executable = "bat"