[interface]
tooltips = true

border_style = "round"
border_color = "$primary-lighten-3"
border_inactive_color = "$primary-darken-3"

pinned_sidebar_width = "20"
file_list_width = "3fr"
preview_sidebar_width = "2fr"
footer_unfocus_width = "10"
footer_focus_width = "20"

preview_error = "Hmm, I think this file got corrupted (or maybe not?)"
preview_binary = "This file is not UTF-8 encoded, so I decline to read it."
preview_start = "print(\"Hello, world!\")"

[settings]
use_recycle_bin = true
filelist_sort_by = "name"
filelist_sort_order = "ascending"

[theme]
default = "nord"

[[custom_theme]]
name = "High Contrast Dark"
primary = "#ffffff"
secondary = "#cccccc"
accent = "#00ff00"
foreground = "#ffffff"
background = "#000000"
success = "#00ff00"
warning = "#ffff00"
error = "#ff0000"
surface = "#1a1a1a"
panel = "#0d0d0d"
is_dark = true

[keybinds]
toggle_pin = ["P"]
toggle_pinned_sidebar = ["S"]
toggle_preview_sidebar = ["I"]
toggle_footer = ["F"]

focus_toggle_pinned_sidebar = ["s"]
focus_file_list = ["escape"]
focus_toggle_preview_sidebar = ["i"] 
focus_toggle_path_switcher = ["slash", "/"]
focus_toggle_search = ["f", "/"]
focus_toggle_processes = ["p"]
focus_toggle_clipboard = ["c"]
focus_toggle_metadata = ["m"]

copy = ["y", "ctrl+c"]
paste = ["p", "ctrl+v"]
cut = ["x", "ctrl+x"]
delete = ["d", "delete"]
rename = ["r", "f2"]
toggle_all = ["%", "ctrl+a"]
new = ["o", "ctrl+n"]

up = ["up", "k"]
down = ["down", "j"]
up_tree = ["left", "h"]
down_tree = ["right", "l", "enter"]
page_up = ["pageup", "ctrl+b"]
page_down = ["pagedown", "ctrl+f"]
home = ["home", "g g"]
end = ["end", "G"]
hist_previous = ["backspace", "u"]
hist_next = ["space", "ctrl+r"]
reload = ["ctrl+r", "f5"]

toggle_visual = ["v"]
select_up = ["shift+up", "K"]
select_down = ["shift+down", "J"]
select_page_up = ["shift+pageup"]
select_page_down = ["shift+pagedown"]
select_home = ["shift+home"]
select_end = ["shift+end"]

[plugins]
[plugins.zoxide]
enabled = true
keybinds = ["z"]
[plugins.bat]
enabled = true
executable = "bat"
