[interface]

[interface.border]
style = "solid"
inactive_color = "$primary-darken-3"
color = "$primary-lighten-3"

[interface.theme]
default = "nord"

[sidebar]
wrap = true
[sidebar.text]
error = "Hmm, I think this file got corrupted (or maybe not?)"
binary = "010101 0101\nJust kidding, this is a binary file"
folder = "Nesting? What's that?"
start = "print(\"Hello, world!\")"

[filelist]
sort_by = "name"
sort_order = "ascending"